name: Draft a GitHub release on tag push

on:
  push:
    tags: [v*]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  check:
    uses: ./.github/workflows/golangci-lint.yaml

  draft-release:
    name: Release on tag push
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    needs: [build, check]
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: What's up?
        run: tree

      - name: Create a GitHub release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true
          files: dist/devzat-*
